security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
         our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
            http_basic: ~
            provider: our_db_provider

    access_control:
           # require ROLE_ADMIN for /admin*
           - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
